<?php

declare(strict_types=1);

use FuzzyFox\Lucide\Generation\EnumEmitter;

it('emits the enum source for a single glyph', function () {
    $expected = <<<'PHP'
        <?php

        declare(strict_types=1);

        namespace FuzzyFox\Lucide;

        /**
         * Generated by the lucide-for-laravel sync — do not edit by hand.
         *
         * One case per Lucide glyph; each case's value is its icon-set name.
         */
        enum Lucide: string
        {
            case Camera = 'lucide-camera';
        }

        PHP;

    expect(EnumEmitter::emit(['camera']))->toBe($expected);
});

it('emits cases in alphabetical-by-glyph order regardless of input order', function () {
    $source = EnumEmitter::emit(['camera', 'anchor', 'box']);

    expect($source)
        ->toContain("    case Anchor = 'lucide-anchor';\n    case Box = 'lucide-box';\n    case Camera = 'lucide-camera';");
});

it("backs each case with the icon-set name lucide-<glyph>", function () {
    $source = EnumEmitter::emit(['alarm-clock-plus']);

    // The value keeps the raw kebab-case glyph even though the case name is
    // transformed, so the case and the icon-set entry can never disagree.
    expect($source)->toContain("    case AlarmClockPlus = 'lucide-alarm-clock-plus';");
});

it('names cases via the case-name transformer (digit runs become words)', function () {
    // `dice-6 → DiceSix` is the transformer's whole-number rule (ADR-0004); the
    // emitter must delegate to it rather than reimplement naming.
    expect(EnumEmitter::emit(['dice-6']))
        ->toContain("    case DiceSix = 'lucide-dice-6';");
});

it('is byte-deterministic and independent of input order', function () {
    expect(EnumEmitter::emit(['camera', 'anchor', 'box']))
        ->toBe(EnumEmitter::emit(['box', 'camera', 'anchor']));
});

it('matches the committed enum-source snapshot', function () {
    $expected = file_get_contents(__DIR__.'/fixtures/Lucide.expected.php');

    expect(EnumEmitter::emit(['camera', 'dice-6', 'alarm-clock-plus']))->toBe($expected);
});
