<?php

declare(strict_types=1);

namespace FuzzyFox\Lucide;

/**
 * Generated by the lucide-for-laravel sync — do not edit by hand.
 *
 * One case per Lucide glyph; each case's value is its icon-set name.
 */
enum Lucide: string
{
    case AlarmClockPlus = 'lucide-alarm-clock-plus';
    case Camera = 'lucide-camera';
    case DiceSix = 'lucide-dice-6';
}
