<?php

declare(strict_types=1);

namespace FuzzyFox\Lucide\Generation;

/**
 * Emits the source of `src/Lucide.php` — the `FuzzyFox\Lucide\Lucide` enum — from
 * an ordered glyph list. One `string`-backed case per glyph, the case name from the
 * case-name transformer (ADR-0004) and the backing value the icon-set name, so the
 * case and the icon-set entry can never disagree (`Lucide::Camera->value` is
 * `'lucide-camera'`). Pure and framework-free — no I/O.
 *
 * Cases are emitted in stable alphabetical-by-glyph order with byte-deterministic
 * output, so a sync of an unchanged set produces an identical file and the rolling
 * PR shows only real glyph changes (ADR-0009 diff hygiene).
 */
final class EnumEmitter
{
    private const HEADER = <<<'PHP'
        <?php

        declare(strict_types=1);

        namespace FuzzyFox\Lucide;

        /**
         * Generated by the lucide-for-laravel sync — do not edit by hand.
         *
         * One case per Lucide glyph; each case's value is its icon-set name.
         */
        enum Lucide: string
        {

        PHP;

    /** @param list<string> $glyphs */
    public static function emit(array $glyphs): string
    {
        sort($glyphs, SORT_STRING);

        $cases = array_map(
            static fn (string $glyph): string => sprintf(
                "    case %s = 'lucide-%s';",
                CaseName::fromGlyph($glyph),
                $glyph,
            ),
            $glyphs,
        );

        return self::HEADER.implode("\n", $cases)."\n}\n";
    }
}
